services:
  mongodb:
    image: mongo:latest
    container_name: mwkvw_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - mwkvw-network

  backend:
    container_name: mwkvw_backend
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: always
    networks:
      - mwkvw-network
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:

networks:
  mwkvw-network:
    driver: bridge